# Generated by Django 5.2.5 on 2025-08-08 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام فاز')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد فاز')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('progress', models.PositiveIntegerField(default=0, help_text='درصد پیشرفت', verbose_name='پیشرفت')),
                ('status', models.CharField(choices=[('planning', 'برنامه\u200cریزی'), ('in_progress', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('on_hold', 'متوقف شده'), ('cancelled', 'لغو شده')], default='planning', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'فاز',
                'verbose_name_plural': 'فازها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام فعالیت')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد فعالیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('progress', models.PositiveIntegerField(default=0, help_text='درصد پیشرفت', verbose_name='پیشرفت')),
                ('status', models.CharField(choices=[('planning', 'برنامه\u200cریزی'), ('in_progress', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('on_hold', 'متوقف شده'), ('cancelled', 'لغو شده')], default='planning', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('parent_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_activities', to='projects.activity', verbose_name='فعالیت والد')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.phase', verbose_name='فاز')),
            ],
            options={
                'verbose_name': 'فعالیت',
                'verbose_name_plural': 'فعالیت\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'phase')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام پروژه')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد پروژه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('progress', models.PositiveIntegerField(default=0, help_text='درصد پیشرفت', verbose_name='پیشرفت')),
                ('status', models.CharField(choices=[('planning', 'برنامه\u200cریزی'), ('in_progress', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('on_hold', 'متوقف شده'), ('cancelled', 'لغو شده')], default='planning', max_length=20, verbose_name='وضعیت')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کارفرما')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project', verbose_name='پروژه'),
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('finish_to_start', 'فعالیت وابسته بعد از تمام شدن فعالیت اصلی شروع می\u200cشود'), ('start_to_start', 'فعالیت وابسته همزمان با فعالیت اصلی شروع میشود'), ('finish_to_finish', 'فعالیت وابسته همزمان با فعالیت اصلی تمام میشود'), ('start_to_finish', 'فعالیت وابسته بعد از شروع فعالیت اصلی تما میشود')], max_length=20, verbose_name='نوع وابستگی')),
                ('lag_time', models.DurationField(blank=True, help_text='زمان تاخیر (مثلا: 2 days, 3 hours)', null=True, verbose_name='زمان تاخیر')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='projects.activity', verbose_name='فعالیت اصلی')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='projects.activity', verbose_name='فعالیت وابسته')),
            ],
            options={
                'verbose_name': 'وابستگی',
                'verbose_name_plural': 'وابستگی\u200cها',
                'ordering': ['activity__name', 'depends_on__name'],
                'unique_together': {('activity', 'depends_on', 'dependency_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='phase',
            unique_together={('name', 'project')},
        ),
    ]
