# Generated by Django 5.2.5 on 2025-08-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependency',
            name='lag_time',
        ),
        migrations.AlterField(
            model_name='dependency',
            name='dependency_type',
            field=models.CharField(choices=[('finish_to_start', 'فعالیت وابسته بعد از تمام شدن فعالیت اصلی شروع می\u200cشود'), ('start_to_start', 'فعالیت وابسته همزمان با فعالیت اصلی شروع میشود'), ('finish_to_finish', 'فعالیت وابسته همزمان با فعالیت اصلی تمام میشود'), ('start_to_finish', 'فعالیت وابسته بعد از شروع فعالیت اصلی تمام میشود')], max_length=20, verbose_name='نوع وابستگی'),
        ),
    ]
